In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [4]:
import webbrowser
website = 'http://en.wikipedia.org/wiki/NFL_win-loss_records'
webbrowser.open(website)

True

In [11]:
nfl_frame = pd.read_clipboard()

In [12]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
0,1,Dallas Cowboys,493,367,1,0.573,1960,860,NFC East
1,1,Tampa Bay Buccaneers,250,393,1,0.514,1976,866,NFC South
2,3,Green Bay Packers,730,553,37,0.567,1921,"1,320",NFC North
3,4,Chicago Bears,744,568,42,0.565,1920,"1,354",NFC North
4,5,Miami Dolphins,439,341,4,0.563,1966,784,AFC East
5,6,New England Patriots[b],476,383,9,0.554,1960,868,AFC East
6,7,New York Giants,684,572,33,0.543,1925,"1,289",NFC East
7,8,Denver Broncos,465,393,10,0.541,1960,868,AFC West
8,9,Minnesota Vikings,457,387,10,0.541,1961,854,NFC North
9,10,Baltimore Ravens,181,154,1,0.540,1996,336,AFC North
10,11,San Francisco 49ers,522,450,14,0.537,1950,986,NFC West
11,12,Indianapolis Colts[c],502,441,7,0.532,1953,950,AFC South
12,13,Oakland Raiders,456,401,11,0.532,1960,868,AFC West
13,14,Pittsburgh Steelers,601,535,20,0.529,1933,"1,156",AFC North
14,15,Kansas City Chiefs,447,409,12,0.522,1960,868,AFC West
15,16,Washington Redskins,586,572,28,0.506,1932,"1,186",NFC East
16,17,Seattle Seahawks,325,318,1,0.505,1976,644,NFC West
17,18,Cleveland Browns,462,466,10,0.498,1950,938,AFC North
18,19,Los Angeles Chargers,426,431,11,0.497,1960,868,AFC West
19,20,Los Angeles Rams,544,554,21,0.496,1937,"1,119",NFC West
20,21,Carolina Panthers,172,179,1,0.490,1995,352,NFC South
21,22,Philadelphia Eagles,555,591,26,0.485,1933,"1,172",NFC East
22,23,Tennessee Titans,413,449,6,0.479,1960,868,AFC South
23,24,Buffalo Bills,400,460,8,0.465,1960,868,AFC East
24,25,Detroit Lions,544,641,32,0.460,1930,"1,217",NFC North
25,26,Cincinnati Bengals,344,408,4,0.458,1968,756,AFC North
26,27,New York Jets,392,468,8,0.456,1960,868,AFC East
27,28,New Orleans Saints,338,427,5,0.442,1967,770,NFC South
28,29,Houston Texans,106,134,0,0.442,2002,240,AFC South
29,30,Jacksonville Jaguars,155,197,0,0.440,1995,352,AFC South
30,31,Atlanta Falcons,341,437,6,0.439,1966,784,NFC South
31,32,Arizona Cardinals,542,732,40,0.428,1920,"1,314",NFC West

In [13]:
nfl_frame.columns

Index(['Rank', 'Team', 'Won', 'Lost', 'Tied', 'Pct.', 'First NFL Season',
       'Total Games', 'Division'],
      dtype='object')

In [17]:
nfl_frame.Rank

0      1
1      1
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
Name: Rank, dtype: int64

In [21]:
nfl_frame['Total Games']

0       860
1       866
2     1,320
3     1,354
4       784
5       868
6     1,289
7       868
8       854
9       336
10      986
11      950
12      868
13    1,156
14      868
15    1,186
16      644
17      938
18      868
19    1,119
20      352
21    1,172
22      868
23      868
24    1,217
25      756
26      868
27      770
28      240
29      352
30      784
31    1,314
Name: Total Games, dtype: object

In [23]:
DataFrame(nfl_frame, columns=['Team', 'First NFL Season', 'Total Games'])

                       Team  First NFL Season Total Games
0            Dallas Cowboys              1960         860
1      Tampa Bay Buccaneers              1976         866
2         Green Bay Packers              1921       1,320
3             Chicago Bears              1920       1,354
4            Miami Dolphins              1966         784
5   New England Patriots[b]              1960         868
6           New York Giants              1925       1,289
7            Denver Broncos              1960         868
8         Minnesota Vikings              1961         854
9          Baltimore Ravens              1996         336
10      San Francisco 49ers              1950         986
11    Indianapolis Colts[c]              1953         950
12          Oakland Raiders              1960         868
13      Pittsburgh Steelers              1933       1,156
14       Kansas City Chiefs              1960         868
15      Washington Redskins              1932       1,186
16         Seattle Seahawks              1976         644
17         Cleveland Browns              1950         938
18     Los Angeles Chargers              1960         868
19         Los Angeles Rams              1937       1,119
20        Carolina Panthers              1995         352
21      Philadelphia Eagles              1933       1,172
22         Tennessee Titans              1960         868
23            Buffalo Bills              1960         868
24            Detroit Lions              1930       1,217
25       Cincinnati Bengals              1968         756
26            New York Jets              1960         868
27       New Orleans Saints              1967         770
28           Houston Texans              2002         240
29     Jacksonville Jaguars              1995         352
30          Atlanta Falcons              1966         784
31        Arizona Cardinals              1920       1,314

In [24]:
# Retrieve the first 5 row by default, passing in an int value n to retrieve n rows
nfl_frame.head()

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
0,1,Dallas Cowboys,493,367,1,0.573,1960,860,NFC East
1,1,Tampa Bay Buccaneers,250,393,1,0.514,1976,866,NFC South
2,3,Green Bay Packers,730,553,37,0.567,1921,"1,320",NFC North
3,4,Chicago Bears,744,568,42,0.565,1920,"1,354",NFC North
4,5,Miami Dolphins,439,341,4,0.563,1966,784,AFC East

In [26]:
# Retrieve the last 5 rows by default, pass in int n to retrieve last 5 rows
nfl_frame.tail()

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
27,28,New Orleans Saints,338,427,5,0.442,1967,770,NFC South
28,29,Houston Texans,106,134,0,0.442,2002,240,AFC South
29,30,Jacksonville Jaguars,155,197,0,0.440,1995,352,AFC South
30,31,Atlanta Falcons,341,437,6,0.439,1966,784,NFC South
31,32,Arizona Cardinals,542,732,40,0.428,1920,"1,314",NFC West

In [29]:
# Get info of row 3
nfl_frame.ix[3]

Rank                            4
Team                Chicago Bears
Won                           744
Lost                          568
Tied                           42
Pct.                        0.565
First NFL Season             1920
Total Games                 1,354
Division                NFC North
Name: 3, dtype: object

In [33]:
# Assign value to a column, fill in all rows in column Stadium with the value Levi's Stadium
nfl_frame['Stadium'] = 'Levi\'s Stadium'
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Dallas Cowboys,493,367,1,0.573,1960,860,NFC East,Levi's Stadium
1,1,Tampa Bay Buccaneers,250,393,1,0.514,1976,866,NFC South,Levi's Stadium
2,3,Green Bay Packers,730,553,37,0.567,1921,"1,320",NFC North,Levi's Stadium
3,4,Chicago Bears,744,568,42,0.565,1920,"1,354",NFC North,Levi's Stadium
4,5,Miami Dolphins,439,341,4,0.563,1966,784,AFC East,Levi's Stadium
5,6,New England Patriots[b],476,383,9,0.554,1960,868,AFC East,Levi's Stadium
6,7,New York Giants,684,572,33,0.543,1925,"1,289",NFC East,Levi's Stadium
7,8,Denver Broncos,465,393,10,0.541,1960,868,AFC West,Levi's Stadium
8,9,Minnesota Vikings,457,387,10,0.541,1961,854,NFC North,Levi's Stadium
9,10,Baltimore Ravens,181,154,1,0.540,1996,336,AFC North,Levi's Stadium
10,11,San Francisco 49ers,522,450,14,0.537,1950,986,NFC West,Levi's Stadium
11,12,Indianapolis Colts[c],502,441,7,0.532,1953,950,AFC South,Levi's Stadium
12,13,Oakland Raiders,456,401,11,0.532,1960,868,AFC West,Levi's Stadium
13,14,Pittsburgh Steelers,601,535,20,0.529,1933,"1,156",AFC North,Levi's Stadium
14,15,Kansas City Chiefs,447,409,12,0.522,1960,868,AFC West,Levi's Stadium
15,16,Washington Redskins,586,572,28,0.506,1932,"1,186",NFC East,Levi's Stadium
16,17,Seattle Seahawks,325,318,1,0.505,1976,644,NFC West,Levi's Stadium
17,18,Cleveland Browns,462,466,10,0.498,1950,938,AFC North,Levi's Stadium
18,19,Los Angeles Chargers,426,431,11,0.497,1960,868,AFC West,Levi's Stadium
19,20,Los Angeles Rams,544,554,21,0.496,1937,"1,119",NFC West,Levi's Stadium
20,21,Carolina Panthers,172,179,1,0.490,1995,352,NFC South,Levi's Stadium
21,22,Philadelphia Eagles,555,591,26,0.485,1933,"1,172",NFC East,Levi's Stadium
22,23,Tennessee Titans,413,449,6,0.479,1960,868,AFC South,Levi's Stadium
23,24,Buffalo Bills,400,460,8,0.465,1960,868,AFC East,Levi's Stadium
24,25,Detroit Lions,544,641,32,0.460,1930,"1,217",NFC North,Levi's Stadium
25,26,Cincinnati Bengals,344,408,4,0.458,1968,756,AFC North,Levi's Stadium
26,27,New York Jets,392,468,8,0.456,1960,868,AFC East,Levi's Stadium
27,28,New Orleans Saints,338,427,5,0.442,1967,770,NFC South,Levi's Stadium
28,29,Houston Texans,106,134,0,0.442,2002,240,AFC South,Levi's Stadium
29,30,Jacksonville Jaguars,155,197,0,0.440,1995,352,AFC South,Levi's Stadium
30,31,Atlanta Falcons,341,437,6,0.439,1966,784,NFC South,Levi's Stadium
31,32,Arizona Cardinals,542,732,40,0.428,1920,"1,314",NFC West,Levi's Stadium

In [36]:
# Set the rows in stadium column to be the values from an array from [0..31]
nfl_frame['Stadium'] = np.arange(32)

In [37]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Dallas Cowboys,493,367,1,0.573,1960,860,NFC East,0
1,1,Tampa Bay Buccaneers,250,393,1,0.514,1976,866,NFC South,1
2,3,Green Bay Packers,730,553,37,0.567,1921,"1,320",NFC North,2
3,4,Chicago Bears,744,568,42,0.565,1920,"1,354",NFC North,3
4,5,Miami Dolphins,439,341,4,0.563,1966,784,AFC East,4
5,6,New England Patriots[b],476,383,9,0.554,1960,868,AFC East,5
6,7,New York Giants,684,572,33,0.543,1925,"1,289",NFC East,6
7,8,Denver Broncos,465,393,10,0.541,1960,868,AFC West,7
8,9,Minnesota Vikings,457,387,10,0.541,1961,854,NFC North,8
9,10,Baltimore Ravens,181,154,1,0.540,1996,336,AFC North,9
10,11,San Francisco 49ers,522,450,14,0.537,1950,986,NFC West,10
11,12,Indianapolis Colts[c],502,441,7,0.532,1953,950,AFC South,11
12,13,Oakland Raiders,456,401,11,0.532,1960,868,AFC West,12
13,14,Pittsburgh Steelers,601,535,20,0.529,1933,"1,156",AFC North,13
14,15,Kansas City Chiefs,447,409,12,0.522,1960,868,AFC West,14
15,16,Washington Redskins,586,572,28,0.506,1932,"1,186",NFC East,15
16,17,Seattle Seahawks,325,318,1,0.505,1976,644,NFC West,16
17,18,Cleveland Browns,462,466,10,0.498,1950,938,AFC North,17
18,19,Los Angeles Chargers,426,431,11,0.497,1960,868,AFC West,18
19,20,Los Angeles Rams,544,554,21,0.496,1937,"1,119",NFC West,19
20,21,Carolina Panthers,172,179,1,0.490,1995,352,NFC South,20
21,22,Philadelphia Eagles,555,591,26,0.485,1933,"1,172",NFC East,21
22,23,Tennessee Titans,413,449,6,0.479,1960,868,AFC South,22
23,24,Buffalo Bills,400,460,8,0.465,1960,868,AFC East,23
24,25,Detroit Lions,544,641,32,0.460,1930,"1,217",NFC North,24
25,26,Cincinnati Bengals,344,408,4,0.458,1968,756,AFC North,25
26,27,New York Jets,392,468,8,0.456,1960,868,AFC East,26
27,28,New Orleans Saints,338,427,5,0.442,1967,770,NFC South,27
28,29,Houston Texans,106,134,0,0.442,2002,240,AFC South,28
29,30,Jacksonville Jaguars,155,197,0,0.440,1995,352,AFC South,29
30,31,Atlanta Falcons,341,437,6,0.439,1966,784,NFC South,30
31,32,Arizona Cardinals,542,732,40,0.428,1920,"1,314",NFC West,31

In [42]:
nfl_frame = nfl_frame.head()

In [43]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Dallas Cowboys,493,367,1,0.573,1960,860,NFC East,AT&T Stadium
1,1,Tampa Bay Buccaneers,250,393,1,0.514,1976,866,NFC South,NaN
2,3,Green Bay Packers,730,553,37,0.567,1921,"1,320",NFC North,NaN
3,4,Chicago Bears,744,568,42,0.565,1920,"1,354",NFC North,NaN
4,5,Miami Dolphins,439,341,4,0.563,1966,784,AFC East,Levi's Stadium

In [44]:
stadiums = Series(["Levi\'s Stadium", "AT&T Stadium"], index=[4,0])
stadiums

4    Levi's Stadium
0      AT&T Stadium
dtype: object

In [47]:
# Change values in the stadium columns. The index in the series stadiums will match the index
# of the value in the dataframe in order to change the value in those rows
nfl_frame['Stadium'] = stadiums
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Dallas Cowboys,493,367,1,0.573,1960,860,NFC East,AT&T Stadium
1,1,Tampa Bay Buccaneers,250,393,1,0.514,1976,866,NFC South,NaN
2,3,Green Bay Packers,730,553,37,0.567,1921,"1,320",NFC North,NaN
3,4,Chicago Bears,744,568,42,0.565,1920,"1,354",NFC North,NaN
4,5,Miami Dolphins,439,341,4,0.563,1966,784,AFC East,Levi's Stadium

In [49]:
data = {'City':['SF', 'LA', 'NYC'],
       'Population':[837000,3880000,8400000]}

In [52]:
# Construct a data frame from a dictionary
city_frame = DataFrame(data)

In [53]:
city_frame

  City  Population
0   SF      837000
1   LA     3880000
2  NYC     8400000

In [54]:
# The reference for DataFrame in pandas module
webbrowser.open('http://pandas.pydata.org/pandas-docs/dev/generated./pandas.DataFrame.html')

True